{
 "title": "Materialize Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage per Cluster Replica",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sql_cluster_replica_cpu_usage{}",
     "legendFormat": "{{ cluster_name }}"
    }
   ]
  },
  {
   "title": "Memory Usage per Cluster Replica",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sql_cluster_replica_memory_usage{}",
     "legendFormat": "{{ cluster_name }}"
    }
   ]
  },
  {
   "title": "Storage Usage per Object",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sql_storage_usage{}",
     "legendFormat": "{{ object_name }} - {{object_type}}"
    }
   ]
  },
  {
   "title": "Source Status",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "sql_source_status{}", "legendFormat": "{{ source_name }}" }
   ]
  },
  {
   "title": "Sink Status",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "sql_sink_status{}", "legendFormat": "{{ sink_name }}" }
   ]
  },
  {
   "title": "Bytes Received per Source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "sql_source_bytes_received{}", "legendFormat": "{{ source_name }}" }
   ]
  },
  {
   "title": "Bytes Committed per Sink",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "sql_sink_bytes_committed{}", "legendFormat": "{{ source_name }}" }
   ]
  },
  {
   "title": "Messages Count per Source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "sql_source_messages_received{}", "legendFormat": "{{ source_name }}" }
   ]
  },
  {
   "title": "Messages Committed per Sink",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "sql_sink_bytes_committed{}", "legendFormat": "{{ cluster_name }}" }
   ]
  }
 ]
}