global:
  scrape_interval: 15s
scrape_configs:
  - job_name: sql_exporter
    scrape_interval: 15s
    static_configs:
      - targets: ['sql-exporter:9237']
        labels:
          instance: sql_exporter
