{
 "title": "Materialize Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Resources Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage per Computing Cluster",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sql_cluster_replica_usage{cluster_type=\"compute\",col=\"cpu_percent\"}",
       "legendFormat": "{{ cluster_name }}"
      }
     ]
    },
    {
     "title": "Memory Usage per Computing Cluster",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sql_cluster_replica_usage{cluster_type=\"compute\",col=\"memory_percent\"}",
       "legendFormat": "{{ cluster_name }}"
      }
     ]
    },
    {
     "title": "Storage Usage per Object",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sql_storage_usage{col=\"size_bytes\",object_type=~\"materialized-view|table\"}",
       "legendFormat": "{{ object_name }} - {{object_type}}"
      }
     ]
    },
    {
     "title": "Approximate Lag per Object",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sql_object_freshness{col=\"approx_lag_ms\"}",
       "legendFormat": "{{ cluster_name }} - {{ replica_name }}"
      }
     ]
    },
    {
     "title": "Query Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sql_query_latency{col=\"avg_latency\"}",
       "legendFormat": "Avg latency"
      },
      {
       "expr": "sql_query_latency{col=\"max_latency\"}",
       "legendFormat": "Max latency"
      },
      {
       "expr": "sql_query_latency{col=\"min_latency\"}",
       "legendFormat": "Min latency"
      }
     ]
    }
   ]
  },
  {
   "title": "Sources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage per Source",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "{cluster_type=\"source\",col=\"cpu_percent\"}",
       "legendFormat": "{{ cluster_name }}"
      }
     ]
    },
    {
     "title": "Memory Usage per Source",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "{cluster_type=\"source\",col=\"memory_percent\"}",
       "legendFormat": "{{ cluster_name }}"
      }
     ]
    },
    {
     "title": "Storage Usage per Object",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sql_storage_usage{col=\"size_bytes\",object_type=\"source\"}",
       "legendFormat": "{{ object_name }} - {{object_type}}"
      }
     ]
    },
    {
     "title": "Bytes Received per Source",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sql_source_statistics{col=\"bytes_received\"}",
       "legendFormat": "{{ source_name }}"
      }
     ]
    },
    {
     "title": "Messages Count per Source",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sql_source_statistics{col=\"messages_received\"}",
       "legendFormat": "{{ source_name }}"
      }
     ]
    },
    {
     "title": "Envelope State Size per Source",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sql_source_statistics{col=\"envelope_state_bytes\"}",
       "legendFormat": "{{ source_name }}"
      }
     ]
    },
    {
     "title": "Envelope State Count per Source",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "sql_source_statistics{col=\"envelope_state_count\"}",
       "legendFormat": "{{ source_name }}"
      }
     ]
    }
   ]
  },
  { "title": "Credit Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 3 },
   "options": {
    "content": "This section displays the current credit usage from clusters.\n\nIt is not intended to show an accurate amount of credit usage but rather to provide a way to visualize and monitor unexpected credit consumption."
   }
  },
  {
   "title": "Consumption Rate per Hour",
   "type": "stat",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{col=\"credits_per_hour\"}",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Per Computing Cluster",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sql_cluster_replica_usage{cluster_type=\"compute\",col=\"credits_per_hour\"}",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Per Source and Sink",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sql_cluster_replica_usage{cluster_type=~\"sink|source\",col=\"credits_per_hour\"}",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Sinks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage per Sink",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sql_cluster_replica_usage{cluster_type=\"sink\",col=\"cpu_percent\"}",
       "legendFormat": "{{ cluster_name }}"
      }
     ]
    },
    {
     "title": "Memory Usage per Sink",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sql_cluster_replica_usage{cluster_type=\"sink\",col=\"memory_percent\"}",
       "legendFormat": "{{ cluster_name }}"
      }
     ]
    },
    {
     "title": "Sink Status",
     "type": "status-history",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sql_sink_statistics{col=\"sink_status_counter\"}",
       "legendFormat": "{{ sink_name }}"
      }
     ]
    },
    {
     "title": "Messages Committed per Sink",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sql_sink_statistics{col=\"messages_committed\"}",
       "legendFormat": "{{ sink_name }}"
      }
     ]
    },
    {
     "title": "Bytes Committed per Sink",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sql_sink_statistics{col=\"bytes_committed\"}",
       "legendFormat": "{{ sink_name }}"
      }
     ]
    }
   ]
  }
 ]
}