version: '2'

services:
  datadog:
    build: datadog
    pid: host
    environment:
     - DD_API_KEY=<API_KEY>
     - DD_SITE=datadoghq.com
     - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
  sql-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: <PSQL_CONNECTION>
      PG_EXPORTER_EXTEND_QUERY_PATH: /queries.yml
    command:
      - "--disable-default-metrics"
      - "--disable-settings-metrics"
      - "--no-collector.database"
      - "--no-collector.bgwriter"
      - "--no-collector.replication_slot"
    volumes:
      - ./queries.yaml:/queries.yml