version: '2'

services:
  datadog:
    build: datadog
    pid: host
    environment:
     - DD_API_KEY=${DD_API_KEY}
     - DD_SITE=datadoghq.com
     - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
  sql-exporter:
    image: justwatch/sql_exporter:latest
    ports:
      - 9237:9237
    environment:
      CONFIG: /config/config.yaml
    volumes:
      - ./config.yaml:/config/config.yaml