version: 2

models:
  - name: avg_bid
    description: 'Computes the average bid price'
    columns:
      - name: symbol
        description: 'The stock ticker'
        tests:
          - not_null
          - unique
      - name: avg_bid
        description: 'The average bid price'
        tests:
          - dbt_utils.expression_is_true:
              expression: '>= 200'
              config:
                schema: 'bid_alert'
                alias: 'avg_bid_threshold_200'
                severity: warn
