services:
  materialized:
    image: materialize/materialized:v0.26.4
    container_name: materialized
    init: true
    ports:
      - 6875:6875
    healthcheck: {test: curl -f localhost:6875, interval: 1s, start_period: 30s}
  cli:
    image: materialize/cli:v0.26.4
    container_name: cli
  dbt:
    build: ./
    container_name: dbt
    init: true
    entrypoint: /bin/bash
    working_dir: /usr/app/dbt/
    ports:
      - 8000:8080
    volumes:
      - ./dbt/profiles.yml:/root/.dbt/profiles.yml
      - ./dbt/:/usr/app/dbt
    stdin_open: true
    tty: true
    depends_on:
      materialized: {condition: service_healthy}
