mz_get_started:
  outputs:
    demo:
      type: materialize
      host: "{{ env_var('MZ_HOST') }}"
      port: 6875
      user: "{{ env_var('MZ_USER') }}"
      password: "{{ env_var('MZ_PASSWORD') }}"
      database: datacouncil2023
      cluster: default
      schema: shop
  target: demo