## Generally, the profiles.yml file never be included in your dbt project but rather
## locally in a .dbt folder. For the purpose of this demo, we have included it here!

materialize_get_started:
  outputs:
    dev:
      type: materialize
      threads: 1
      host: <host>
      port: 6875
      user: <user@domain.com>
      pass: <password>
      database: materialize
      cluster: auction_house
      schema: public
      sslmode: require
  target: dev
