services:
  helper:
    container_name: helper
    build:
      context: ./helper
    init: true
    environment:
      MZ_HOST: ${MZ_HOST:-materialized}
      MZ_PORT: ${MZ_PORT:-6875}
      MZ_USER: ${MZ_USER:-materialize}
      MZ_PASSWORD: ${MZ_PASSWORD:-materialize}
      MZ_DATABASE: ${MZ_DATABASE:-materialize}
      KAFKA_BROKER: ${KAFKA_BROKER:-broker:29092}
      KAFKA_SASL_MECHANISM: ${KAFKA_SASL_MECHANISM:-plain}
      KAFKA_USERNAME: ${KAFKA_USERNAME:-admin}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD:-admin-secret}

  backend:
    container_name: backend
    build:
      context: ./backend
    init: true
    ports:
      - 4000:4000
    depends_on:
      - helper
    environment:
      MZ_HOST: ${MZ_HOST:-materialized}
      MZ_PORT: ${MZ_PORT:-6875}
      MZ_USER: ${MZ_USER:-materialize}
      MZ_PASSWORD: ${MZ_PASSWORD:-materialize}
      MZ_DATABASE: ${MZ_DATABASE:-materialize}
      KAFKA_BROKER: ${KAFKA_BROKER:-broker:29092}
      KAFKA_SASL_MECHANISM: ${KAFKA_SASL_MECHANISM:-plain}
      KAFKA_USERNAME: ${KAFKA_USERNAME:-admin}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD:-admin-secret}

  frontend:
    container_name: frontend
    build:
      context: ../antennas-postgres/frontend
    init: true
    ports:
      - 3000:3000
    depends_on:
      - backend

  microservice:
    container_name: microservice
    build:
      context: ./microservice
    init: true
    depends_on:
      - helper
      - backend
    environment:
      MZ_HOST: ${MZ_HOST:-materialized}
      MZ_PORT: ${MZ_PORT:-6875}
      MZ_USER: ${MZ_USER:-materialize}
      MZ_PASSWORD: ${MZ_PASSWORD:-materialize}
      MZ_DATABASE: ${MZ_DATABASE:-materialize}
      KAFKA_BROKER: ${KAFKA_BROKER:-broker:29092}
      KAFKA_SASL_MECHANISM: ${KAFKA_SASL_MECHANISM:-plain}
      KAFKA_USERNAME: ${KAFKA_USERNAME:-admin}
      KAFKA_PASSWORD: ${KAFKA_PASSWORD:-admin-secret}
