version: '2'

services:
  grafana:
    image: grafana/grafana-enterprise:8.2.0
    ports:
      - 3000:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    volumes:
      - ./misc/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./misc/datasources:/etc/grafana/provisioning/datasources
      - ./misc/dashboards:/var/lib/grafana/dashboards
  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  sql-exporter:
    image: justwatch/sql_exporter:latest
    ports:
      - 9237:9237
    environment:
      CONFIG: /config/config.yml
    volumes:
      - ./config.yml:/config/config.yml
