version: 2

models:
  - name: public
    description: 'Raw market order data'

  - name: market_orders
    description: 'Converts market order data to proper data types'

  - name: avg_bid
    description: 'Computes the average bid price'
    columns:
      - name: symbol
        description: 'The stock ticker'
        tests:
          - not_null
      - name: avg
        description: 'The average bid price'
