name: CI
on:
  push:
    branches: [main, bump/*]
  pull_request:

  workflow_dispatch:
    inputs:
      version:
        description: Materialize version
        default: unstable

  # Run against the latest unstable every night to catch problems before they
  # ship in a release.
  schedule:
    - cron: '0 5 * * *'

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        docker-compose: [1.29.2, v2.1.1]
        demo:
          - ecommerce
          - ecommerce-redpanda
          - feature-store
          - http-logs
          - wikirecent
          - dbt-get-started
          - billing
          - chbench
          - antennas-postgres
          - antennas-kafka
    steps:
      - uses: actions/checkout@v1
      - uses: KengoTODA/actions-setup-docker-compose@v1.0.4
        with:
          version: ${{ matrix.docker-compose }}
      - name: Bump Materialize
        run: |
          pip install -r .github/tools/requirements.txt
          .github/tools/bump.py materialize ${{ github.event.inputs.version || 'unstable' }}
        if: github.event.schedule || github.event.inputs.version
      - name: Run and test demo
        run: |
          cd ${{ matrix.demo }}
          $GITHUB_WORKSPACE/.github/tests/${{ matrix.demo }}.sh
      - name: Dump logs
        run: |
          cd ${{ matrix.demo }}
          docker-compose logs > $GITHUB_WORKSPACE/docker-compose.log
        if: always()
      - name: Upload logs
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.demo }}-docker-compose.log
          path: docker-compose.log
        if: always()

  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: pip install pre-commit==2.16.0
      - run: pre-commit run --all-files

  report:
    runs-on: ubuntu-20.04
    needs: [test, lint]
    if: failure() && github.event.schedule
    steps:
      - uses: actions-ecosystem/action-slack-notifier@v1
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          message: |
            Demos failed against Materialize version "${{ github.event.inputs.version || 'unstable' }}".
          channel: eng-notifications
          color: red
          verbose: true
